### ISSUE TITLE
Feedback on Reakit

### ISSUE THREAD

**Issue by diegohaz** [wearefuturegov/bucks-api#1]
Hey @jhackett1 

I'm following public repositories that use Reakit, including this one. I saw that you removed it from the project (which is totally fine 😊).

I'm constantly trying to improve the library, and I think your feedback would be really valuable.

Which problems did you have with Reakit? How could it be better for you? What do you think Reach UI does better?

Thank you 🙏

**Comment by jhackett1** [comment]
hello! ran into issues with ie11 support, and was experiencing a strange half-second lag in the interface after a tap on a mobile device, so tried out reach-ui instead.

have since found that reach-ui seems patchy when it comes to ssr instead, so will probably just build a custom component for what i need!

**Comment by diegohaz** [comment]
Thank you for the feedback @jhackett1

Just to check, does the half-second lag happen on this page too? https://reakit.io/docs/menu

**Comment by jhackett1** [comment]
not quite as bad, but yes! with a motorola g6, chrome.
